name: built_value_nested_list_bug
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  built_value: ^8.0.0
  built_collection: ^5.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.0.0
  built_value_generator: ^8.0.0
